#!/usr/bin/env bash
set -euo pipefail

nvidia_pci="pci-0000:01:00.0"
nvidia_card="/dev/dri/by-path/${nvidia_pci}-card"
nvidia_render="/dev/dri/by-path/${nvidia_pci}-render"
output="${XDG_CACHE_HOME:-$HOME/.cache}/niri/renderer-auto.kdl"
mode="auto"
mark_active=false

while (($#)); do
    case "$1" in
        --force-external)
            mode="external"
            ;;
        --force-internal)
            mode="internal"
            ;;
        --output)
            shift
            output="${1:?--output requires a path}"
            ;;
        --mark-active)
            mark_active=true
            ;;
        *)
            printf 'Unknown argument: %s\n' "$1" >&2
            exit 2
            ;;
    esac
    shift
done

if [[ "$mode" == "auto" ]]; then
    mode="internal"

    if [[ -e "$nvidia_card" ]]; then
        card="$(basename "$(readlink -f "$nvidia_card")")"

        for status_file in /sys/class/drm/"${card}"-*/status; do
            [[ -e "$status_file" ]] || continue
            if [[ "$(<"$status_file")" == "connected" ]]; then
                mode="external"
                break
            fi
        done
    fi
fi

mkdir -p "$(dirname "$output")"
tmp="${output}.tmp.$$"
trap 'rm -f "$tmp"' EXIT

if [[ "$mode" == "external" ]]; then
    if [[ ! -e "$nvidia_render" ]]; then
        printf 'NVIDIA render device is missing: %s\n' "$nvidia_render" >&2
        exit 1
    fi

    cat >"$tmp" <<EOF
// Generated by ~/.config/niri/scripts/update-renderer-profile.sh
// External display is connected to the NVIDIA GPU.
debug {
    render-drm-device "$nvidia_render"
    wait-for-frame-completion-before-queueing
}
EOF
else
    cat >"$tmp" <<'EOF'
// Generated by ~/.config/niri/scripts/update-renderer-profile.sh
// No NVIDIA-connected external display; let niri select the Intel iGPU.
EOF
fi

mv -f "$tmp" "$output"
trap - EXIT

if $mark_active; then
    runtime_dir="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
    cache_active="${XDG_CACHE_HOME:-$HOME/.cache}/niri/renderer-profile-active"
    mkdir -p "$(dirname "$cache_active")"
    printf '%s\n' "$mode" >"$runtime_dir/niri-renderer-profile-active"
    printf '%s\n' "$mode" >"$cache_active"
fi

printf '%s\n' "$mode"
