[general]
import = ["~/.config/alacritty/themes/current.toml"]

[window]
padding.x = 20
padding.y = 20 

decorations = "Buttonless"

[font]
normal = { family = "FiraCodeNerdFont", style = "Retina"}

[cursor.style]
blinking = "Always"

[bell] 
animation = "EaseOutExpo"
duration = 0

[cursor]
smooth_motion = true
smooth_motion_factor = 1.0
smooth_motion_spring = 0.3
block_replace_shape = "Block"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
